### ISSUE TITLE
Ошибка отправки 

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#11]
если отправить строчку 
print("sdf")
на сервер придет
 print(sdf")

**Comment by k0oda** [comment]
**CLIENT**
![image](https://user-images.githubusercontent.com/39520144/57966087-4ce64180-796f-11e9-8a3f-1b5300410b2d.png)
**SERVER**
![image](https://user-images.githubusercontent.com/39520144/57966088-553e7c80-796f-11e9-983e-29319becae2c.png)
