### ISSUE TITLE
При отправке сообщения с кодом на языке программирования появляется ошибка

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#17]
// symbols.cpp: определяет точку входа для консольного приложения.
 
#include "stdafx.h"
#include <iostream>
using namespace std;
 
int main(int argc, char* argv[])
{
    char string[] = "this is string - "; // объявление и инициализация строки
    cout << "Enter the string: ";
    char in_string[500]; // строковый массив для ввода 
    gets(in_string); // функция gets() считывает все введённые символы с пробелами до тех пор, пока не будет нажата клавиша Enter 
    cout << string << in_strinEnter a message or enter "/r" to receive new messages > g << endl; // вывод строкового значения
    system("pause");
    return 0;
}Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a message or enter "/r" to receive new messages > Enter a mes

сообщение которое отправлялось 

/ symbols.cpp: определяет точку входа для консольного приложения.
 
#include "stdafx.h"
#include <iostream>
using namespace std;
 
int main(int argc, char* argv[])
{
    char string[] = "this is string - "; // объявление и инициализация строки
    cout << "Enter the string: ";
    char in_string[500]; // строковый массив для ввода 
    gets(in_string); // функция gets() считывает все введённые символы с пробелами до тех пор, пока не будет нажата клавиша Enter 
    cout << string << in_string << endl; // вывод строкового значения
    system("pause");
    return 0;
}

**Comment by k0oda** [comment]
Вообще программа не предназначена для отправки столь сложных строк в силу того что она ограничена терминалом и его возможностями
Но в ближайшее время я подумаю над решением этой проблемы

**Comment by k0oda** [comment]
**CLIENT**
![image](https://user-images.githubusercontent.com/39520144/57970978-d0bd1f80-79a9-11e9-9870-0ae679b2bc12.png)
**SERVER**
![image](https://user-images.githubusercontent.com/39520144/57970982-dc104b00-79a9-11e9-9365-320368045aca.png)
**ПОЛУЧЕННОЕ СООБЩЕНИЕ В КЛИЕНТЕ**
![image](https://user-images.githubusercontent.com/39520144/57970989-ef231b00-79a9-11e9-91e9-7151db73562d.png)
