### ISSUE TITLE
Отправка пустой строки

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#3]
🍽
если вставить данные эмодзи в консоль и нажать два раза enter то на сервер отправляется пустая строка (или строка с невидимыми символами)

**Comment by centralhardware** [comment]
при попытке вставить любую строку возникает данная проблема

**Comment by centralhardware** [comment]
возникает при отправке невидимого символа

**Comment by k0oda** [comment]
![Screenshot_20190711_151716](https://user-images.githubusercontent.com/39520144/61038553-0a7d3600-a3ef-11e9-9c2e-2fa08b684874.png)
Проблемы нет в Linux системе, терминал способен обработать не все эмодзи а только поддерживаемые, в случае отправки не поддерживаемого эмодзи отправляется прямоугольник
