### ISSUE TITLE
Не понятная ошибка 

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#5]
Enter a message or enter "/r" to receive new messages > ааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
Enter a message or enter "/r" to receive new messages > ааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
Enter a message or enter "/r" to receive new messages > ааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
Enter a message or enter "/r" to receive new messages > ааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
Enter a message or enter "/r" to receive new messages > ааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааааа
Enter a message or enter "/r" to receive new messages > ^M
Enter a message or enter "/r" to receive new messages > ^?
Enter a message or enter "/r" to receive new messages > /r
Traceback (most recent call last):
  File "client.py", line 83, in <module>
    sending = Thread(target=client.send_data())
  File "client.py", line 38, in send_data
    self.receive_data()
  File "client.py", line 21, in receive_data
    data = self.sock.recv(1024).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 1023: unexpected end of data

**Comment by k0oda** [comment]
**CLIENT**
![image](https://user-images.githubusercontent.com/39520144/57966299-bd8e5d80-7971-11e9-8707-22ece48f92ac.png)
**SERVER**
![image](https://user-images.githubusercontent.com/39520144/57966302-c8e18900-7971-11e9-8ca7-3e9329626656.png)

Проблема решена
