### ISSUE TITLE
Ошибка подключения клиента 

### ISSUE THREAD

**Issue by centralhardware** [kukree/tuichat#7]
если количество подключений больше чем лимит подключений в клиенте который не обрабатывается сервером, клиент делает вид что все нормально и сообщения уходят.  Новые сообщения не появляются

**Comment by k0oda** [comment]
Сервер просто напросто не пускает нового клиента на сервер, но позже я добавлю обработку этого случая и клиент будет просто отключаться и не сможет отправлять никакие сообщения
Точнее сервер не обрабатывает нового клиента вообще, сообщения никак не принимает и не выводит
